apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-manifests 
    repoURL: https://github.com/pszeptynski/argocd-playground
    targetRevision: HEAD
  # Sync policy:  empty = manual
  syncPolicy: {}
